name: Generate CEF bundle releases on x86_64

on: workflow_call

jobs:
  generate-x86-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Generate a release bundle of CEF for Open592
        run: |
          ls -lah
          ./generate.sh x86_64
      - uses: actions/upload-artifact@v3
        with:
          name: cef-x86-64
          path: ${{ github.workspace }}/working-dir/outputs/*.tar.bz2
          if-no-files-found: error