name: Generate CEF releases

# TODO: Update to only run on new tags
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  build:
    needs: [checkout]
    uses: ./.github/workflows/generate-all.yml
  release:
    needs: [build, checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts/
      - name: Create release
        id: create-release
        run: |
          cd ${{ github.workspace }}/artifacts/
          ls -lah
