name: Generate CEF releases

# TODO: Update to only run on new tags
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - arm
          - arm64
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Generate a release bundle of CEF for Open592
        run: |
          ls -lah
          ./generate.sh
      - uses: actions/upload-artifact@v3
        with:
          name: cef-${{ matrix.arch }}
          path: ${{ github.workspace }}/working-dir/outputs/*.tar.bz2
          if-no-files-found: error
