name: Generate CEF bundle releases

on:
  push:
    tags:
      - '*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  build:
    needs: [checkout]
    uses: ./.github/workflows/generate-all.yml
  release:
    needs: [build, checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/artifacts/cef-*/*.tar.bz2
          artifactErrorsFailBuild: true
          body: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
